config/routes.rb
Carrollsite::Application.routes.draw do
  devise_for :users do
    get "sign_up"  => "devise/registrations#new" 
    get "sign_in"  => "devise/sessions#new"    
    get "sign_out" => "devise/sessions#destroy"
  end  
  root to: "homes#index"

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # before_filter :authenticate_user!
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  def index

  end  
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/homes/_form.html.haml
= form_for @home do |f|
  - if @home.errors.any?
    #error_explanation
      %h2= "#{pluralize(@home.errors.count, "error")} prohibited this home from being saved:"
      %ul
        - @home.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/homes/edit.html.haml
%h1 Editing home

= render 'form'

= link_to 'Show', @home
\|
= link_to 'Back', homes_path

app/views/homes/index.html.haml
.navbar
	.navbar-inverse.navbar-fixed-top
		.container
			- if user_signed_in?
				= current_user.email
				%br 
				= link_to 'Log Out', sign_out_path
.container 	
	.starter-template			
		.home-login
			%h1 Welcome to Carrollsite CMS

			.login
				= render new_user_session_path
			.OR			
			.registration
				= render new_user_registration_path

app/views/homes/new.html.haml
%h1 New home

= render 'form'

= link_to 'Back', homes_path

app/views/homes/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_home_path(@home)
\|
= link_to 'Back', homes_path

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title Carrollsite
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Carrollsite
    %link{:href => "http://www.google.com/fonts/#UsePlace:use/Collection:Crimson+Text:400italic|Joti+One", :rel => "stylesheet", :type => "text/css"}/
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = yield

app/views/layouts/users.html.haml
!!!
%html
  %head
    %title Carrollsite
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = yield

app/views/users/_sign_in.html.erb
<h2>Sign in</h2>

<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true, :class => 'input-block-level', :placeholder => 'Email address' %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password , :class => 'input-block-level', :placeholder => 'Password' %></div>

  <% if devise_mapping.rememberable? -%>
    <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
  <% end -%>

  <div><%= f.submit "Sign in" , {:class => 'btn btn-large btn-primary btn-block'} %></div>
<% end %>

<%= render "devise/shared/links" %>

app/views/users/_sign_up.html.erb
<h2>Sign up</h2>

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true, :class => 'input-block-level', :placeholder => 'Email address' %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password, :class => 'input-block-level', :placeholder => 'Password' %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation, :class => 'input-block-level', :placeholder => 'Password confirmation' %></div>

  <div><%= f.submit "Sign up", {:class => 'btn btn-large btn-primary btn-block'} %></div>
<% end %>